// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/24/2026, 6:17:39 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/joao/Desktop/1/faculdade/projeto abolicao/2026.1/Site Projeto Abolição Site/Projeto Abolição/Projeto Abolição/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/joao/Desktop/1/faculdade/projeto abolicao/2026.1/Site Projeto Abolição Site/Projeto Abolição/Projeto Abolição/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/joao/Desktop/1/faculdade/projeto abolicao/2026.1/Site Projeto Abolição Site/Projeto Abolição/Projeto Abolição/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/joao/Desktop/1/faculdade/projeto abolicao/2026.1/Site Projeto Abolição Site/Projeto Abolição/Projeto Abolição/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/joao/Desktop/1/faculdade/projeto abolicao/2026.1/Site Projeto Abolição Site/Projeto Abolição/Projeto Abolição/app/plugins/**/*.{js,ts,mjs}","/Users/joao/Desktop/1/faculdade/projeto abolicao/2026.1/Site Projeto Abolição Site/Projeto Abolição/Projeto Abolição/app/composables/**/*.{js,ts,mjs}","/Users/joao/Desktop/1/faculdade/projeto abolicao/2026.1/Site Projeto Abolição Site/Projeto Abolição/Projeto Abolição/app/utils/**/*.{js,ts,mjs}","/Users/joao/Desktop/1/faculdade/projeto abolicao/2026.1/Site Projeto Abolição Site/Projeto Abolição/Projeto Abolição/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/joao/Desktop/1/faculdade/projeto abolicao/2026.1/Site Projeto Abolição Site/Projeto Abolição/Projeto Abolição/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/joao/Desktop/1/faculdade/projeto abolicao/2026.1/Site Projeto Abolição Site/Projeto Abolição/Projeto Abolição/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/joao/Desktop/1/faculdade/projeto abolicao/2026.1/Site Projeto Abolição Site/Projeto Abolição/Projeto Abolição/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;